baseURL = "http://frankanthny.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Frank Anthony"
[markup.goldmark.renderer]
unsafe = true
