author = "Themefisher"
contact_form_action = "#contact_form_action = \"https://formspree.io/admin@frankanthny.com/\""
description = "This is meta description"
logo = "/images/fa-logo-7.png"
logo_width = "200px"
[navigation_button]
enable = true
label = "Get Started"
link = "home"
[preloader]
enable = true
preloader = ""
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
